<a href="https://colab.research.google.com/github/diegocavazos53/analisis-matricial/blob/principal/Kassimali_Cap%C3%ADtulo_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Capítulo 2
Sección 2.3

In [ ]:
import numpy as np

# 2.1

# Crear dos matrices de 3x3
matriz_A = np.array([[9, -3,  2], [ 3, -5, 4], [-2, -4,  6]])
matriz_B = np.array([[8, -7, -1], [-7,  9, 0], [-1,  0, -6]])

# Sumar las matrices
matriz_C = matriz_A + matriz_B
matriz_D = matriz_A - matriz_B

print("Matriz A:")
print(matriz_A)
print("\nMatriz B:")
print(matriz_B)
print("\nResultado de la suma:")
print(matriz_C)
print("\nResultado de la resta:")
print(matriz_D)

Matriz A:
[[ 9 -3  2]
 [ 3 -5  4]
 [-2 -4  6]]

Matriz B:
[[ 8 -7 -1]
 [-7  9  0]
 [-1  0 -6]]

Resultado de la suma:
[[ 17 -10   1]
 [ -4   4   4]
 [ -3  -4   0]]

Resultado de la resta:
[[  1   4   3]
 [ 10 -14   4]
 [ -1  -4  12]]


In [ ]:
# 2.2

# Crear dos matrices de 4x3
matriz_A = np.array([[6, -1, -8, -4], [-8, -4,  3, 6], [-5, -2, -3,  7]])
matriz_B = np.array([[5, -2,  4,  1], [ 4,  5, -6, 7], [-1,  2,  8, -5]])

# Multiplicar y sumar las matrices
# El producto de un escalar por una matriz se hace con el operador '*'
matriz_C = 2*matriz_A + matriz_B
matriz_D = matriz_A - 3*matriz_B

print("Matriz A:")
print(matriz_A)
print("\nMatriz B:")
print(matriz_B)
print("\nMatriz C:")
print(matriz_C)
print("\nMatriz D:")
print(matriz_D)

Matriz A:
[[ 6 -1 -8 -4]
 [-8 -4  3  6]
 [-5 -2 -3  7]]

Matriz B:
[[ 5 -2  4  1]
 [ 4  5 -6  7]
 [-1  2  8 -5]]

Matriz C:
[[ 17  -4 -12  -7]
 [-12  -3   0  19]
 [-11  -2   2   9]]

Matriz D:
[[ -9   5 -20  -7]
 [-20 -19  21 -15]
 [ -2  -8 -27  22]]


In [37]:
# 2.3

# Crear dos "matrices"
matriz_A = np.array([[-5], [2], [-8], [4]])
matriz_B = np.array([[3, -7, 1, -6]])
# Aunque sea un renglón, lleva los paréntesis rectos dobles para ser matriz.

# Producto punto se lleva a cabo con el operador '@'
matriz_C = matriz_A @ matriz_B
matriz_D = matriz_B @ matriz_A
print("Matriz C:")
print(matriz_C)
print("Matriz D:")
print(matriz_D)

Matriz C:
[[-15  35  -5  30]
 [  6 -14   2 -12]
 [-24  56  -8  48]
 [ 12 -28   4 -24]]
Matriz D:
[[-61]]


In [ ]:
# 2.4

# Crear dos matrices
matriz_A = np.array([[1, -10, -2, -6], [3, -8, -12, 8]])
matriz_B = np.array([[2, -10], [6, -1], [-2, 10], [5, 9]])

# Producto matricial
matriz_C = matriz_A @ matriz_B
matriz_D = matriz_B @ matriz_A

print("Matriz C:")
print(matriz_C)
print("Matriz D:")
print(matriz_D)

Matriz C:
[[-84 -74]
 [ 22 -70]]
Matriz D:
[[ -28   60  116  -92]
 [   3  -52    0  -44]
 [  28  -60 -116   92]
 [  32 -122 -118   42]]


In [ ]:
# 2.5

# Crear dos matrices
matriz_A = np.array([[5,  7, -2], [ 7, 9, 0], [-2, 0, 8]])
matriz_B = np.array([[2, -8,  1], [-8, 3, 5], [ 1, 5, 6]])

# Producto
matriz_C = matriz_A @ matriz_B
matriz_D = matriz_B @ matriz_A

print("Matriz C:")
print(matriz_C)
print("Matriz D:")
print(matriz_D)

Matriz C:
[[-48 -29  28]
 [-58 -29  52]
 [  4  56  46]]
Matriz D:
[[-48 -58   4]
 [-29 -29  56]
 [ 28  52  46]]


In [ ]:
# 2.6

# Crear dos matrices
matriz_A = np.array([[3, 4, 2], [2, 3, -8], [-3, 0, 6]])
matriz_B = np.array([[8, 1, 6, -2], [6, -2, 5, 8], [3, 0, -1, 0]])

# Producto
matriz_C = matriz_A @ matriz_B

print("Matriz C:")
print(matriz_C)

Matriz C:
[[ 54  -5  36  26]
 [ 10  -4  35  20]
 [ -6  -3 -24   6]]


In [ ]:
# 2.7

# La biblioteca de NumPy se encarga de esto.
# Usar el operador @ o la función np.dot()

In [15]:
# 2.8

# Crear dos matrices
matriz_A = np.array([[14, -5, 11], [-3, 18, -9]])
matriz_B = np.array([[12, -7, 6, 0], [2, 9, 15, -13], [10, -4, -5, 8]])

# Demostración
# La transpuesta de una matriz se obtiene con .T o con la función np.transpose()
matriz_C = (matriz_A @ matriz_B).T
matriz_D = matriz_B.T @ matriz_A.T
matriz_D2 = np.dot(np.transpose(matriz_B), np.transpose(matriz_A))

print("Matriz C (AB)^T:")
print(matriz_C)
print("Matriz D B^T*A^T:")
print(matriz_D)
print("Matriz D2 B^T*A^T:")
print(matriz_D2)
print("Lo que demuestra que (AB)^T = B^T * A^T")

Matriz C (AB)^T:
[[ 268  -90]
 [-187  219]
 [ -46  297]
 [ 153 -306]]
Matriz D B^T*A^T:
[[ 268  -90]
 [-187  219]
 [ -46  297]
 [ 153 -306]]
Matriz D2 B^T*A^T:
[[ 268  -90]
 [-187  219]
 [ -46  297]
 [ 153 -306]]
Lo que demuestra que (AB)^T = B^T * A^T


In [17]:
# 2.9

# Crear tres matrices
matriz_A = np.array([[-9, 0], [13, 20], [8, -3], [-11, -5]])
matriz_B = np.array([[15, -1, -4], [6, 16, 9]])
matriz_C = np.array([[-7, 10, 6, 0], [-1, 2, -8, -2], [16, 12, 2, 8]])

# Demostración
matriz_D = (matriz_A @ matriz_B @ matriz_C).T
matriz_E = matriz_C.T @ matriz_B.T @ matriz_A.T

print("Matriz D (ABC)^T:")
print("Matriz E C^T * B^T * A^T")
print(matriz_D)
print(matriz_E)
print("Lo que demuestra que (ABC)^T = C^T * B^T * A^T")

Matriz D (ABC)^T:
Matriz E C^T * B^T * A^T
[[ 1512  -464 -1602  1418]
 [ -900  5300   200 -2100]
 [ -810  -310   942  -620]
 [  270   410  -360   130]]
[[ 1512  -464 -1602  1418]
 [ -900  5300   200 -2100]
 [ -810  -310   942  -620]
 [  270   410  -360   130]]
Lo que demuestra que (ABC)^T = C^T * B^T * A^T


In [19]:
# 2.10

# Crear dos matrices
matriz_A = np.array([[40, -10, -25], [-10, 15, 12], [-25, 12, 30]])
matriz_B = np.array([[5, 7, -3], [-7, 8, 4], [-3, -4, 9]])

# Triple producto:
matriz_C = matriz_B.T @ matriz_A @ matriz_B

print("Matriz C, B^T * A * B:")
print(matriz_C)

Matriz C, B^T * A * B:
[[ 1451   889 -2132]
 [  889  2912 -2683]
 [-2132 -2683  5484]]


In [22]:
# 2.11

# Crear dos matrices
matriz_A = np.array([[300, -100],
                     [-100, 200]])
matriz_B = np.array([[0.6, 0.8, -0.6, -0.8],
                     [-0.8, 0.6, 0.8, -0.6]])

# Triple producto:
matriz_C = matriz_B.T @ matriz_A @ matriz_B

print("Matriz C, B^T  * A * B:")
print(matriz_C)

Matriz C, B^T  * A * B:
[[ 332.   76. -332.  -76.]
 [  76.  168.  -76. -168.]
 [-332.  -76.  332.   76.]
 [ -76. -168.   76.  168.]]


In [ ]:
# 2.12

# La biblioteca de NumPy se encarga de esto.

In [24]:
import sympy as sp
from sympy import symbols, Matrix, sin, cos, tan

# 2.13

# Definimos las variables simbólicas
x = symbols('x')

# Creamos la matriz simbólica
matriz_A = Matrix([[sin(x)**2, -3*x**3, -6*x],
                   [-6*x**2, cos(x)**2, 5],
                   [7, 3*sin(x), tan(x)]])

# Derivamos la matriz simbólica con respecto a x
matriz_B = sp.diff(matriz_A, x)

print("Matriz A:")
display(matriz_A)
print("\nMatriz B:")
display(matriz_B)

Matriz A:


Matrix([
[sin(x)**2,   -3*x**3,   -6*x],
[  -6*x**2, cos(x)**2,      5],
[        7,  3*sin(x), tan(x)]])


Matriz B:


Matrix([
[2*sin(x)*cos(x),          -9*x**2,            -6],
[          -12*x, -2*sin(x)*cos(x),             0],
[              0,         3*cos(x), tan(x)**2 + 1]])

In [26]:
# 2.14

# Definimos las variables simbólicas
x = symbols('x')

# Creamos las matrices simbólicas
matriz_A = Matrix([[-3*x, 5],
                   [4*x**2, -x**3],
                   [-7, 5*x],
                   [2*x**3, -x**2]])
matriz_B = Matrix([[2*x**2, -x],
                   [-12*x, 8],
                   [2*x**3, -3*x**2],
                   [-1, 6*x]])

# Derivamos con respecto a x
matriz_C = sp.diff(matriz_A+matriz_B, x)

print("d(A+B)/dx:")
display(matriz_C)

d(A+B)/dx:


Matrix([
[ 4*x - 3,      -1],
[8*x - 12, -3*x**2],
[  6*x**2, 5 - 6*x],
[  6*x**2, 6 - 2*x]])

In [27]:
# 2.15

# Definimos las variables simbólicas
x = symbols('x')

# Creamos las matrices simbólicas
matriz_A = Matrix([[4*x, 2, -5*x**2],
                   [2, -3*x**3, -x],
                   [-5*x**2, -x, 7]])
matriz_B = Matrix([[-5*x**3, -x],
                   [6, -3*x**2],
                   [2*x**2, 4*x]])

# Derivamos con respecto a x
matriz_C = sp.diff(matriz_A @ matriz_B, x)

print("d(AB)/dx:")
display(matriz_C)

d(AB)/dx:


Matrix([
[          -120*x**3,   -60*x**2 - 20*x],
[           -90*x**2, 45*x**4 - 8*x - 2],
[125*x**4 + 28*x - 6,      24*x**2 + 28]])

In [28]:
# 2.16

# Definimos las variables simbólicas
x, y, z = symbols('x y z')

# Creamos la matriz simbólica
matriz_A = Matrix([[x**2, -y**2, -2*z**2],
                   [-y**2, 3*x*y, -y*z],
                   [2*z**2, -y*z, 4*x*z]])

# Derivamos con respecto a x
matriz_C = sp.diff(matriz_A, x)
matriz_D = sp.diff(matriz_A, y)
matriz_E = sp.diff(matriz_A, z)

print("dA/dx:")
display(matriz_C)
print("dA/dy:")
display(matriz_D)
print("dA/dz:")
display(matriz_E)

dA/dx:


Matrix([
[2*x,   0,   0],
[  0, 3*y,   0],
[  0,   0, 4*z]])

dA/dy:


Matrix([
[   0, -2*y,  0],
[-2*y,  3*x, -z],
[   0,   -z,  0]])

dA/dz:


Matrix([
[  0,  0, -4*z],
[  0,  0,   -y],
[4*z, -y,  4*x]])

In [30]:
# 2.17

# Definimos las variables simbólicas
x, L = symbols('x L')

# Creamos la matriz simbólica
matriz_A = Matrix([[6*x**2, -x**3, 9],
                   [-x**3, 2*x**4, 4*x],
                   [9, 4*x, 5*x**3]])

# Integramos con respecto a x
matriz_B = sp.integrate(matriz_A, (x, 0, L)) # Tuple

print("int(Adx), 0, L:")
display(matriz_B)

int(Adx), 0, L:


Matrix([
[ 2*L**3,  -L**4/4,      9*L],
[-L**4/4, 2*L**5/5,   2*L**2],
[    9*L,   2*L**2, 5*L**4/4]])

In [31]:
# 2.18

# Definimos las variables simbólicas
x, L = symbols('x L')

# Creamos la matriz simbólica
matriz_A = Matrix([[2*x, -sin(x), 2*cos(x)**2],
                   [-sin(x), 5, -4*x**3],
                   [2*cos(x)**2, -4*x**3, (1-x**2)]])

# Integramos con respecto a x
matriz_B = sp.integrate(matriz_A, (x, 0, L)) # Tuple

print("int(Adx), 0, L:")
display(matriz_B)

int(Adx), 0, L:


Matrix([
[             L**2, cos(L) - 1, L + sin(L)*cos(L)],
[       cos(L) - 1,        5*L,             -L**4],
[L + sin(L)*cos(L),      -L**4,       -L**3/3 + L]])

In [32]:
# 2.19

# Definimos las variables simbólicas
x, L = symbols('x L')

# Creamos las matrices simbólicas
matriz_A = Matrix([[-x**3, 2*x**2, 3],
                   [2*x, -x**2, 2*x**3]])
matriz_B = Matrix([[-2*x, x**2],
                   [5, -2*x],
                   [3*x**3, -3]])

# Integramos con respecto a x
matriz_C = sp.integrate(matriz_A @ matriz_B, (x, 0, L)) # Tuple

print("int(Adx), 0, L:")
display(matriz_C)

int(Adx), 0, L:


Matrix([
[2*L**5/5 + 9*L**4/4 + 10*L**3/3, -L**6/6 - L**4 - 9*L],
[              6*L**7/7 - 3*L**3,              -L**4/2]])

In [34]:
# 2.20

# Crear dos matrices
matriz_A = np.array([[-0.28, -0.96, 0, 0],
                     [0.96, -0.28, 0, 0],
                     [0, 0, -0.28, -0.96],
                     [0, 0, 0.96, -0.28]])
matriz_B = np.array([[-0.28, 0.96, 0, 0],
                     [0.96, -0.28, 0, 0],
                     [0, 0, -0.28, 0.96],
                     [0, 0, 0.96, -0.28]])

print("Si A*A^T da la matriz identidad, la matriz es ortogonal.")
matriz_C = matriz_A @ matriz_A.T
matriz_D = matriz_B @ matriz_B.T
print("Matriz C, A*A^T:")
print(matriz_C)
print("Matriz D, B*B^T:")
print(matriz_D)
print("La matriz D no es ortogonal")

Si A*A^T da la matriz identidad, la matriz es ortogonal.
Matriz C, A*A^T:
[[ 1.00000000e+00 -2.32702746e-17  0.00000000e+00  0.00000000e+00]
 [-2.32702746e-17  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00 -2.32702746e-17]
 [ 0.00000000e+00  0.00000000e+00 -2.32702746e-17  1.00000000e+00]]
Matriz D, B*B^T:
[[ 1.     -0.5376  0.      0.    ]
 [-0.5376  1.      0.      0.    ]
 [ 0.      0.      1.     -0.5376]
 [ 0.      0.     -0.5376  1.    ]]
La matriz D no es ortogonal


Sección 2.4

In [35]:
# 2.21

# Matriz de coeficientes
matriz_coeficientes = np.array([[2, -3, 1],
                                [-9, 5, 3],
                                [4, 7, -8]])
# Vector de resultados
vector_resultados = np.array([-18, 18, 53])
# Solución
solucion = np.linalg.solve(matriz_coeficientes, vector_resultados)

print("\nLa solución del sistema de ecuaciones es:")
print(f"x = {solucion[0]:.2f}")
print(f"y = {solucion[1]:.2f}")
print(f"z = {solucion[2]:.2f}")


La solución del sistema de ecuaciones es:
x = -2.00
y = 3.00
z = -5.00


In [36]:
# 2.22

# Matriz de coeficientes
matriz_coeficientes = np.array([[20, -9, 15],
                                [-9, 16, -5],
                                [15, -5, 18]])
# Vector de resultados
vector_resultados = np.array([354, -275, 307])
# Solución
solucion = np.linalg.solve(matriz_coeficientes, vector_resultados)

print("\nLa solución del sistema de ecuaciones es:")
print(f"x = {solucion[0]:.2f}")
print(f"y = {solucion[1]:.2f}")
print(f"z = {solucion[2]:.2f}")


La solución del sistema de ecuaciones es:
x = 6.00
y = -11.00
z = 9.00


In [38]:
# 2.23

# Matriz de coeficientes
matriz_coeficientes = np.array([[4, -2, 3],
                                [3, 5, -1],
                                [1, -4, 2]])
# Vector de resultados
vector_resultados = np.array([37.2, -7.2, 30.3])
# Solución
solucion = np.linalg.solve(matriz_coeficientes, vector_resultados)

print("\nLa solución del sistema de ecuaciones es:")
print(f"x = {solucion[0]:.2f}")
print(f"y = {solucion[1]:.2f}")
print(f"z = {solucion[2]:.2f}")


La solución del sistema de ecuaciones es:
x = 8.70
y = -7.50
z = -4.20


In [40]:
# 2.24

# Matriz de coeficientes
matriz_coeficientes = np.array([[6, 15, -24, 40],
                                [15, 9, -13, 0],
                                [-24, -13, 8, -11],
                                [40, 0, -11, 5]])
# Vector de resultados
vector_resultados = np.array([190.9, 69.8, -96.3, 119.35])
# Solución
solucion = np.linalg.solve(matriz_coeficientes, vector_resultados)

print("\nLa solución del sistema de ecuaciones es:")
print(f"x = {solucion[0]:.2f}")
print(f"y = {solucion[1]:.2f}")
print(f"z = {solucion[2]:.2f}")
print(f"w = {solucion[3]:.2f}")


La solución del sistema de ecuaciones es:
x = 1.75
y = -0.00
z = -3.35
w = 2.50


In [41]:
# 2.25

# Matriz de coeficientes
matriz_coeficientes = np.array([[2, -5, 8, 11],
                                [10, 7, 4, -1],
                                [-3, 9, 5, -6],
                                [1, -4, -2, 9]])
# Vector de resultados
vector_resultados = np.array([39, 127, 58, -14])
# Solución
solucion = np.linalg.solve(matriz_coeficientes, vector_resultados)

print("\nLa solución del sistema de ecuaciones es:")
print(f"x = {solucion[0]:.2f}")
print(f"y = {solucion[1]:.2f}")
print(f"z = {solucion[2]:.2f}")
print(f"w = {solucion[3]:.2f}")


La solución del sistema de ecuaciones es:
x = 6.00
y = 7.00
z = 5.00
w = 2.00


In [ ]:
# 2.26

# La biblioteca de NumPy se encarga de esto.

In [44]:
# 2.27

# Crea matriz
matriz_A = np.array([[5, 3, -4],
                     [3, 8, -2],
                     [-4, -2, 7]])
# Obtener la inversa
matriz_B = np.linalg.inv(matriz_A)

print("La inversa de la matriz A es:")
print(matriz_B)

La inversa de la matriz A es:
[[ 0.44444444 -0.11111111  0.22222222]
 [-0.11111111  0.16239316 -0.01709402]
 [ 0.22222222 -0.01709402  0.26495726]]


In [45]:
# 2.28

# Crea matriz
matriz_A = np.array([[6, -4, 1],
                     [-1, 9, 3],
                     [4, 2, 5]])
# Obtener la inversa
matriz_B = np.linalg.inv(matriz_A)

print("La inversa de la matriz A es:")
print(matriz_B)

La inversa de la matriz A es:
[[ 0.3046875  0.171875  -0.1640625]
 [ 0.1328125  0.203125  -0.1484375]
 [-0.296875  -0.21875    0.390625 ]]


In [46]:
# 2.29

# Crea matriz
matriz_A = np.array([[7, -6, 3, -2],
                     [-6, 4, -1, 5],
                     [3, -1, 8, 9],
                     [-2, 5, 9, 2]])
# Obtener la inversa
matriz_B = np.linalg.inv(matriz_A)

print("La inversa de la matriz A es:")
print(matriz_B)

La inversa de la matriz A es:
[[-0.62656073 -0.71396141  0.28490352 -0.12372304]
 [-0.71396141 -0.69580023  0.23950057 -0.05221339]
 [ 0.28490352  0.23950057 -0.09875142  0.13053348]
 [-0.12372304 -0.05221339  0.13053348 -0.08059024]]


In [47]:
# 2.30

# Crea matriz
matriz_A = np.array([[5, -7, -3, 11],
                     [10, -6, -13, 2],
                     [-1, 12, 8, -4],
                     [-9, 7, -5, 6]])
# Obtener la inversa
matriz_B = np.linalg.inv(matriz_A)

print("La inversa de la matriz A es:")
print(matriz_B)

La inversa de la matriz A es:
[[ 0.03915256  0.05098534  0.07208422 -0.04071867]
 [ 0.00487232  0.03745595  0.08452604  0.03493279]
 [ 0.04132771 -0.05729325  0.02053334 -0.04298082]
 [ 0.08748423 -0.01496498  0.02662374  0.0290164 ]]
